### ISSUE TITLE
update FAQ page

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mineshspc.com#30]
- [x] the "Environments" thing doesn't make any sense, we should remove it
- [x] update the list of problems with links to problems from last year as well as a link to my blog

**Comment by ezrichards** [comment]
Completed as per [aaae02b](https://github.com/ColoradoSchoolOfMines/mineshspc.com/commit/aaae02baeafd818fad7f5af02ab3b601bcf11d1c).
