### ISSUE TITLE
Emails say to reply to noreply

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/mineshspc.com#45]
Emails say at the bottom to reply to the email, but the email is noreply@mineshspc.com; this is confusing

![Screenshot 2023-03-04 072334](https://user-images.githubusercontent.com/42894274/222907791-9e63d133-bdd3-4512-a2f9-0d34dfb57cbc.png)

**Comment by sumnerevans** [comment]
I had a `Reply-To` header that was to `support@mineshspc.com` but I can see how that could be confusing.
