### ISSUE TITLE
Odd spacing on team management (low priority)

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/mineshspc.com#46]
Low priority issue, but it seems like the styling/spacing on this page is pretty inconsistent. I'm happy to look into this if needed.

![Screenshot 2023-03-04 072723](https://user-images.githubusercontent.com/42894274/222907982-1f821419-3680-43e0-86ef-27442024f703.png)

**Comment by sumnerevans** [comment]
What do you think is inconsistent?

**Comment by ezrichards** [comment]
Well, the spacing for the student data is all in line, whereas the division/in-person data is sort of just oddly spaced above it. It might be more readable to just have everything stick to the ": "

**Comment by sumnerevans** [comment]
I'm going to convert this to a table. That's what this list should be anyway.

**Comment by sumnerevans** [comment]
![image](https://user-images.githubusercontent.com/16734772/222915778-8faeef17-48ac-48a3-a711-64ddf29d3e60.png)
