### ISSUE TITLE
add site info page

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mineshspc.com#74]
something like: https://rocky.icpc.io/mines/

probably not necessary for this year, but would be nice to have so people don't as so many questions

**Comment by ezrichards** [comment]
add day-of logistics for teachers (like parking etc) for future years

**Comment by ezrichards** [comment]
Maybe we refactor the "Rules" page into an "Info" page? Or would they be better separate?

**Comment by ezrichards** [comment]
Clarify in rules how many teams teachers are allowed to bring (we are maybe too lenient with this at the moment)

**Comment by ezrichards** [comment]
Completed via 1c283c5
