### ISSUE TITLE
Create registration form

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mineshspc.com#8]
potential flow:

* teacher enters email
* verify teacher email
* teacher fills out the rest of the form
* teacher enters student emails (Kattis emails)
* students must then verify their emails

**Comment by ezrichards** [comment]
It may be useful to have a button before the form which changes which form is visible: i.e., I am a teacher | I am a student (or student's guardian).

If it's a student/their guardian, then they can do their Docusign stuff on the website. This may speed up the registration process and minimize the day-of stuff. If it's a teacher, display the teacher form.

It would be nice to have an embedded Docusign form or at least use the API. One potential problem is saving the form if they accidentally close out or need to come back later.

Also, assuming we use the "Rules" page, maybe a checkbox or signature at the end which says "I agree to all rules as listed by the site, which are subject to change."

**Comment by sumnerevans** [comment]
I think that the way that we should handle this is to also ask for the student's parent's email addresses during login (or a checkbox to use the student's email if they are 18+), and then send their parents an email that will allow them to sign the docusign. We can just use GUIDs and such to gate access I think.

**Comment by ezrichards** [comment]
Another quick thought on this: including a download link for our forms (liability + photo release) inside of the form is probably a good idea. We'll need to wait for the actual updated forms to be done though.

**Comment by sumnerevans** [comment]
I was thinking about this, and I wonder if we even actually need to use docusign. A lot of websites just require you to do an "esignature" with a checkbox and typing your name. We should ask Christine about that
